site_name: Epistemic Virtues Knowledge Base

theme:
  name: material

nav:
  - Home: index.md # Landing page/introduction
  - Tutorials: # Learning-oriented
    - "First Virtue Practice": tutorials/first-iv-practice.md
    - "Building a Classroom Culture of Curiosity": tutorials/classroom-curiosity-culture.md
    - "Socratic Seminar": tutorials/facilitating-socratic-seminar.md
    - "Learning to Notice Intellectual Virtues in Everyday Life": tutorials/notice-iv-in-everyday-life.md
  - How-To Guides: # Problem-solving
    - "How to Respond When Students Make Overconfident Claims": how-to-guides/respond-to-overconfidence.md
    - "How to Model Good Epistemic Habits Without Preaching": how-to-guides/how-to-model-virtues.md
    - "Model Intellectual Humility": how-to-guides/model-intellectual-humility.md
    - "Facilitate Difficult Discussions": how-to-guides/facilitate-difficult-discussions.md
  - Reference: # Information lookup
    - "Virtues Overview": reference/virtues-overview.md
    - "Virtues and Vices": reference/virtues-vices.md
    - "Glossary": reference/glossary.md
    - "Bibliography": reference/bibliography.md
    - "Books/Podcasts/Interviews": reference/books-podcasts-interviews-list.md
  - Explanation: # Understanding
    - "Why Epistemic Virtues Matter": explanation/why-epistemic-virtues-matter.md
    - “Why Intellectual Virtues Are More Than Skills”: explanation/why-i-v-are-more-than-skills.md
    - "Metacognition and Virtues": explanation/metacognition-and-virtues.md
    - "Philosophy for Children": explanation/philosophy-for-children.md
    - "Jason Baehr's Framework": explanation/baehr-framework.md
    - "Formal vs Informal Education": explanation/formal-vs-informal-education.md
  - Personas: # Supporting material
    - "Who is the Knowledge Base for?": personas/index.md
    - "Self-directed Learner": personas/self-directed-learner.md
    - "K12 Educator": personas/k12-educator.md
    - "University Instructor": personas/university-instructor.md
    - "Homeschooler parent": personas/parent-homeschooler.md
  - Templates: # Supporting material
    - "Tutorial Template": templates/tutorial-template.md
    - "How-to Guide Template": templates/how-to-template.md
    - "Reference Template": templates/reference-template.md
    - "Explanation Template": templates/explanation-template.md

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/