name: style-check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Markdown lint
        run: |
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/*.md" "#site" "#.venv" "#node_modules"

      - name: YAML lint
        run: |
          python3 -m pip install --upgrade pip
          pip install yamllint
          yamllint -c .yamllint.yml .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: MkDocs build (strict)
        run: |
          pip install mkdocs-material
          mkdocs build --strict